//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationCWebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int Id { get; set; }
        public string address1 { get; set; }
        public string citi { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string homePhone { get; set; }
        public string cellPhone { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    }
}
