//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationCWebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Famiglie
    {
        public string CodFamiglia { get; set; }
        public string DesFamiglia { get; set; }
    }
}
