//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationCWebForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sophyDB1Entities1 : DbContext
    {
        public sophyDB1Entities1()
            : base("name=sophyDB1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<Articoli> Articolis { get; set; }
        public virtual DbSet<Famiglie> Famiglies { get; set; }
        public virtual DbSet<personal> personals { get; set; }
        public virtual DbSet<Person> People { get; set; }
    
        public virtual ObjectResult<personByName_Result> personByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<personByName_Result>("personByName", nameParameter);
        }
    
        public virtual ObjectResult<personOrderByName_Result> personOrderByName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<personOrderByName_Result>("personOrderByName");
        }
    }
}
