//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplicationCWebForm.AgeCalculation {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoWorkOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateDaysOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgesYMDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WebApplicationCWebForm.Properties.Settings.Default.WebApplicationCWebForm_AgeCalculation_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoWorkCompletedEventHandler DoWorkCompleted;
        
        /// <remarks/>
        public event CalculateDaysCompletedEventHandler CalculateDaysCompleted;
        
        /// <remarks/>
        public event AgesCompletedEventHandler AgesCompleted;
        
        /// <remarks/>
        public event AgesYMDCompletedEventHandler AgesYMDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DoWork", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DoWork() {
            this.Invoke("DoWork", new object[0]);
        }
        
        /// <remarks/>
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        /// <remarks/>
        public void DoWorkAsync(object userState) {
            if ((this.DoWorkOperationCompleted == null)) {
                this.DoWorkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoWorkOperationCompleted);
            }
            this.InvokeAsync("DoWork", new object[0], this.DoWorkOperationCompleted, userState);
        }
        
        private void OnDoWorkOperationCompleted(object arg) {
            if ((this.DoWorkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CalculateDays", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CalculateDays(int day, [System.Xml.Serialization.XmlIgnoreAttribute()] bool daySpecified, int Month, [System.Xml.Serialization.XmlIgnoreAttribute()] bool MonthSpecified, int year, [System.Xml.Serialization.XmlIgnoreAttribute()] bool yearSpecified, out int CalculateDaysResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CalculateDaysResultSpecified) {
            object[] results = this.Invoke("CalculateDays", new object[] {
                        day,
                        daySpecified,
                        Month,
                        MonthSpecified,
                        year,
                        yearSpecified});
            CalculateDaysResult = ((int)(results[0]));
            CalculateDaysResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CalculateDaysAsync(int day, bool daySpecified, int Month, bool MonthSpecified, int year, bool yearSpecified) {
            this.CalculateDaysAsync(day, daySpecified, Month, MonthSpecified, year, yearSpecified, null);
        }
        
        /// <remarks/>
        public void CalculateDaysAsync(int day, bool daySpecified, int Month, bool MonthSpecified, int year, bool yearSpecified, object userState) {
            if ((this.CalculateDaysOperationCompleted == null)) {
                this.CalculateDaysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateDaysOperationCompleted);
            }
            this.InvokeAsync("CalculateDays", new object[] {
                        day,
                        daySpecified,
                        Month,
                        MonthSpecified,
                        year,
                        yearSpecified}, this.CalculateDaysOperationCompleted, userState);
        }
        
        private void OnCalculateDaysOperationCompleted(object arg) {
            if ((this.CalculateDaysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateDaysCompleted(this, new CalculateDaysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Ages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Ages([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DOB dbo, out int AgesResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AgesResultSpecified, out int days, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool daysSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string yourAge) {
            object[] results = this.Invoke("Ages", new object[] {
                        dbo});
            AgesResult = ((int)(results[0]));
            AgesResultSpecified = ((bool)(results[1]));
            days = ((int)(results[2]));
            daysSpecified = ((bool)(results[3]));
            yourAge = ((string)(results[4]));
        }
        
        /// <remarks/>
        public void AgesAsync(DOB dbo) {
            this.AgesAsync(dbo, null);
        }
        
        /// <remarks/>
        public void AgesAsync(DOB dbo, object userState) {
            if ((this.AgesOperationCompleted == null)) {
                this.AgesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgesOperationCompleted);
            }
            this.InvokeAsync("Ages", new object[] {
                        dbo}, this.AgesOperationCompleted, userState);
        }
        
        private void OnAgesOperationCompleted(object arg) {
            if ((this.AgesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgesCompleted(this, new AgesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AgesYMD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgesYMD(int year, [System.Xml.Serialization.XmlIgnoreAttribute()] bool yearSpecified, int month, [System.Xml.Serialization.XmlIgnoreAttribute()] bool monthSpecified, int day, [System.Xml.Serialization.XmlIgnoreAttribute()] bool daySpecified, out int AgesYMDResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AgesYMDResultSpecified, out int days, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool daysSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string yourAge) {
            object[] results = this.Invoke("AgesYMD", new object[] {
                        year,
                        yearSpecified,
                        month,
                        monthSpecified,
                        day,
                        daySpecified});
            AgesYMDResult = ((int)(results[0]));
            AgesYMDResultSpecified = ((bool)(results[1]));
            days = ((int)(results[2]));
            daysSpecified = ((bool)(results[3]));
            yourAge = ((string)(results[4]));
        }
        
        /// <remarks/>
        public void AgesYMDAsync(int year, bool yearSpecified, int month, bool monthSpecified, int day, bool daySpecified) {
            this.AgesYMDAsync(year, yearSpecified, month, monthSpecified, day, daySpecified, null);
        }
        
        /// <remarks/>
        public void AgesYMDAsync(int year, bool yearSpecified, int month, bool monthSpecified, int day, bool daySpecified, object userState) {
            if ((this.AgesYMDOperationCompleted == null)) {
                this.AgesYMDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgesYMDOperationCompleted);
            }
            this.InvokeAsync("AgesYMD", new object[] {
                        year,
                        yearSpecified,
                        month,
                        monthSpecified,
                        day,
                        daySpecified}, this.AgesYMDOperationCompleted, userState);
        }
        
        private void OnAgesYMDOperationCompleted(object arg) {
            if ((this.AgesYMDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgesYMDCompleted(this, new AgesYMDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApplicationC")]
    public partial class DOB {
        
        private int dayField;
        
        private bool dayFieldSpecified;
        
        private int monthField;
        
        private bool monthFieldSpecified;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        public int Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaySpecified {
            get {
                return this.dayFieldSpecified;
            }
            set {
                this.dayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonthSpecified {
            get {
                return this.monthFieldSpecified;
            }
            set {
                this.monthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DoWorkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CalculateDaysCompletedEventHandler(object sender, CalculateDaysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateDaysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateDaysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int CalculateDaysResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CalculateDaysResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgesCompletedEventHandler(object sender, AgesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int AgesResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AgesResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int days {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool daysSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string yourAge {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgesYMDCompletedEventHandler(object sender, AgesYMDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgesYMDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgesYMDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int AgesYMDResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AgesYMDResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int days {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool daysSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string yourAge {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
}

#pragma warning restore 1591